baseURL = "https://xenodochial-johnson-2c8705.netlify.com/"
theme = "biztrox-hugo"
summaryLength = "10"
DefaultContentLanguage = "en"
enableRobotsTXT = true
enableGitInfo = true
disableLanguages = ["Fr"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "© Copyright 2020 ISCON Statistical Services. All Rights Reserved."

[author]
    name = "ISCON Statistics"
    email = "chetan.prajapati@live.com"

[params]

author = "ISCON Statistical Services"
mail = "chetan.prajapati@live.com"
mobile = "+44 7392 339 862"
copyright = "© Copyright 2020 ISCON Statistical Services. All Rights Reserved."
description = "Experienced and professional statistician offers reliable statistical consulting services online to researchers, businesses and PhD students. Hire RSS(UK) accredited freelance statistician for in-depth data analysis and statistical modelling in R, SPSS, STATA. Ask for statistics help in dissertation, medical statistics"
logo = "images/logo.png"
gmapAPI = ""
mapLatitude = ""
mapLongitude = ""
mapMarker = "images/marker.png"
googleAnalitycsID = ""
mailchimpFormAction = ""
mailchimpFormName = ""

[Language]

  [Languages.en]
  languageName = "En"
  languageCode = "en-us"
  weight = 1
  title = "ISCON Statistical Consulting | Hire freelance Statistician Online "
  home = "Home"

  [Languages.en.menu]

    [[Languages.en.menu.nav]]
    name = "About"
    URL = "/about"
    weight = 5

    [[Languages.en.menu.nav]]
    name = "Services"
    URL = "/statistical-consulting-services"
    hasChildren = true
    weight = 2


      [[Languages.en.menu.nav]]
      parent = "Services"
      name = "Research Design & Methodology"
      URL = "/statistical-consulting-services/research-design-methodology/"
      pre = "Get expert statistical advice for your reseach"
      weight = "21"
      [[Languages.en.menu.nav]]
      parent = "Services"
      name = "Data Visualisation"
      URL = "/statistical-consulting-services/data-visualisation"
      pre = "Your data tells a story, Let's us help you to create it"
      weight = "22"
      [[Languages.en.menu.nav]]
      parent = "Services"
      name = "Statistical Analysis & Modelling"
      URL = "/statistical-consulting-services/statistical-analysis-modelling"
      pre = "Get in-depth analysis and report from expert statistician"
      weight = "23"
      [[Languages.en.menu.nav]]
      parent = "Services"
      name = "Dissertation statistical consulting"
      URL = "/statistical-consulting-services/dissertation-statistical-consulting"
      pre = "Let us help you to make your disseration a success with expert statistics help"
      weight = "24"
      [[Languages.en.menu.nav]]
      parent = "Services"
      name = "Survey Design & Analysis"
      URL = "/statistical-consulting-services/survey-design-analysis"
      pre = "Let us help you design and analyse your survey"
      weight = "25"
      [[Languages.en.menu.nav]]
      parent = "Services"
      name = "Clinical-trials Design & Analysis"
      URL = "/statistical-consulting-services/clinical-trials-design-analysis"
      pre = "Let us help you to design, conduct and analyse your trial data"
      weight = "27"
      [[Languages.en.menu.nav]]
      parent = "Services"
      name = "Epidemiology & Genetics"
      URL = "/statistical-consulting-services/epidemiology-genetics"
      pre = "Get help from expert genetic epidemiologist"
      weight = "28"
      [[Languages.en.menu.nav]]
      parent = "Services"
      name = "Statistics Training"
      URL = "/statistical-consulting-services/statistics-training"
      pre = "Let us help you to empower your collagues with interctive statistics training"
      weight = "29"

    [[Languages.en.menu.nav]]
    name = "Case Studies"
    URL = "/case-studies"
    weight = 3

    [[Languages.en.menu.nav]]
    name = "Learning Centre"
    URL = "/learn-statistics"
    weight = 4


      # Quote Button
      [Languages.en.params.quoteBtn]
      enable = true
      btnText = "Talk to Statistician"
      btnURL = "#"

      # cta
      [Languages.en.params.cta]
      enable = true
      bgImage = "images/background/cta.jpg"
      title = "Are You Ready to Unlock the Hidden Potential and Value of Your Data?"
      titleSM = "<em>Connect with ISCON and see what we can do for you.</em>"
      btnText = "Let’s get in touch"
      btnURL = "#"

      # statistical software
      [Languages.en.params.logoSlider]
      enable = true
      title = "Proficient in wide array of statistical software and tools"
      titleSM = ""
        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/statistical-software/R-statistical-software.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/statistical-software/STATA-statistical-software.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/statistical-software/IBM-SPSS-statistical-software.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/statistical-software/WinBugs-MCMC-software.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/statistical-software/StatXact-exact-tests.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/statistical-software/MLWin-Multi-level-model.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/statistical-software/GGPLOT2-R.png"
        URL = "#"

        [[Languages.en.params.logoSlider.sliderItem]]
        image = "images/statistical-software/plotly.png"
        URL = "#"

      # footer
      [Languages.en.params.footer]
      logo = "/images/logo-footer.png"
      content = "62 Maple close, Bristol, BS34 6HH"
      email = "admin@isocon-statistics.com"

      # service links
      services = "Services"

      # quickLinks
      quickLink = "Quick Link"

      # subscribe
      subscribe = "Subscribe Us"
      subscribeContent = "Lorem ipsum dolor sit amet, consect etur adipisicing. elit sed do eiusmod."

      # copyright
      copyright = "© Copyright 2020 ISCON Statistical Services. All Rights Reserved."

        # social icon
        [[Languages.en.params.footer.socialIcon]]
        icon = "ti-facebook"
        URL = "#"

        [[Languages.en.params.footer.socialIcon]]
        icon = "ti-twitter-alt"
        URL = "#"

        [[Languages.en.params.footer.socialIcon]]
        icon = "ti-vimeo-alt"
        URL = "#"

        [[Languages.en.params.footer.socialIcon]]
        icon = "ti-linkedin"
        URL = "#"

        # service links
        [[Languages.en.params.footer.service]]
        serviceItem = "Company History"
        URL = "#"

        [[Languages.en.params.footer.service]]
        serviceItem = "About Us"
        URL = "#"

        [[Languages.en.params.footer.service]]
        serviceItem = "Contact Us"
        URL = "#"

        [[Languages.en.params.footer.service]]
        serviceItem = "Service"
        URL = "#"

        [[Languages.en.params.footer.service]]
        serviceItem = "Privacy Policy"
        URL = "#"

        # quick links
        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "Pricing"
        URL = "#"

        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "FAQs"
        URL = "#"

        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "Contact Us"
        URL = "#"

        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "Service"
        URL = "#"

        [[Languages.en.params.footer.quickLinks]]
        quickLinkItem = "Privacy Policy"
        URL = "#"

        # bottom links
        [[Languages.en.params.footer.links]]
          name = "Sitemap"
          URL = "#"

        [[Languages.en.params.footer.links]]
          name = "Terms of Use"
          URL = "#"

        [[Languages.en.params.footer.links]]
          name = "Privacy & Cookies Policy"
          URL = "#"


      # share blog post
      [[Languages.en.params.sharePost]]
      icon = "ti-facebook"
      URL = "#"

      [[Languages.en.params.sharePost]]
      icon = "ti-twitter-alt"
      URL = "#"

      [[Languages.en.params.sharePost]]
      icon = "ti-linkedin"
      URL = "#"

      [[Languages.en.params.sharePost]]
      icon = "ti-google"
      URL = "#"

